---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ansible-tower
  namespace: tower
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ansible-tower
  template:
    metadata:
      labels:
        app: ansible-tower
        version: v1
    spec:
      containers:
      - name: tower
        image: dynatraceacm/ansibletower:3.3.1-1-2
